version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./Frontend/my-project
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
